version: '3.1'

services:
  phoenix:
    build:
      context: .
    ports:
      - "4000:4000"
    depends_on:
      - phoenix_db
      - web
  phoenix_db:
    image: postgres:9.6
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
  web:
    image: nginx
    volumes:
      - ./test/www:/usr/share/nginx/html
    ports:
      - "8080:80"
    environment:
      - NGINX_HOST=foobar.com
      - NGINX_PORT=80

volumes:
  pgdata: